In [1]:
import pandas as pd
import math
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential, Model, model_from_json
from tensorflow.keras.models import load_model, save_model
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.losses import MeanSquaredError, SparseCategoricalCrossentropy
from tensorflow.keras.metrics import RootMeanSquaredError, Accuracy
from tensorflow.keras.optimizers import Adam
import DataFunctionsNoPres as data
from tcn import tcn

2024-06-04 17:58:27.246370: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-06-04 17:58:27.302622: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-06-04 17:58:27.302657: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-06-04 17:58:27.304642: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-06-04 17:58:27.315030: I tensorflow/core/platform/cpu_feature_guar

In [2]:
import os

files = os.listdir("Data10Tensors/User1")

if len(files) == 0:
    DATA_PROCESSED = 0
else:
    DATA_PROCESSED = 1

if DATA_PROCESSED == 0:
    print("User1...")
    # User1 bag
    data.process_data_for_paper_model("../User1/220617/Bag_Motion.txt", "Data10Tensors/User1/User1_10tensors_220617_bag.csv")
    data.process_data_for_paper_model("../User1/260617/Bag_Motion.txt", "Data10Tensors/User1/User1_10tensors_260617_bag.csv")
    data.process_data_for_paper_model("../User1/270617/Bag_Motion.txt", "Data10Tensors/User1/User1_10tensors_270617_bag.csv")

    # User1 hand
    data.process_data_for_paper_model("../User1/220617/Hand_Motion.txt", "Data10Tensors/User1/User1_10tensors_220617_hand.csv")
    data.process_data_for_paper_model("../User1/260617/Hand_Motion.txt", "Data10Tensors/User1/User1_10tensors_260617_hand.csv")
    data.process_data_for_paper_model("../User1/270617/Hand_Motion.txt", "Data10Tensors/User1/User1_10tensors_270617_hand.csv")

    # User1 hips
    data.process_data_for_paper_model("../User1/220617/Hips_Motion.txt", "Data10Tensors/User1/User1_10tensors_220617_hips.csv")
    data.process_data_for_paper_model("../User1/260617/Hips_Motion.txt", "Data10Tensors/User1/User1_10tensors_260617_hips.csv")
    data.process_data_for_paper_model("../User1/270617/Hips_Motion.txt", "Data10Tensors/User1/User1_10tensors_270617_hips.csv")

    print("User2...")
    # User2 bag
    data.process_data_for_paper_model("../User2/140617/Bag_Motion.txt", "Data10Tensors/User2/User2_10tensors_140617_bag.csv")
    data.process_data_for_paper_model("../User2/140717/Bag_Motion.txt", "Data10Tensors/User2/User2_10tensors_140717_bag.csv")
    data.process_data_for_paper_model("../User2/180717/Bag_Motion.txt", "Data10Tensors/User2/User2_10tensors_180717_bag.csv")

    # User2 hand
    data.process_data_for_paper_model("../User2/140617/Hand_Motion.txt", "Data10Tensors/User2/User2_10tensors_140617_hand.csv")
    data.process_data_for_paper_model("../User2/140717/Hand_Motion.txt", "Data10Tensors/User2/User2_10tensors_140717_hand.csv")
    data.process_data_for_paper_model("../User2/180717/Hand_Motion.txt", "Data10Tensors/User2/User2_10tensors_180717_hand.csv")

    # User2 hips
    data.process_data_for_paper_model("../User2/140617/Hips_Motion.txt", "Data10Tensors/User2/User2_10tensors_140617_hips.csv")
    data.process_data_for_paper_model("../User2/140717/Hips_Motion.txt", "Data10Tensors/User2/User2_10tensors_140717_hips.csv")
    data.process_data_for_paper_model("../User2/180717/Hips_Motion.txt", "Data10Tensors/User2/User2_10tensors_180717_hips.csv")

    print("User3...")
    # User3 bag
    data.process_data_for_paper_model("../User3/140617/Bag_Motion.txt", "Data10Tensors/User3/User3_10tensors_140617_bag.csv")
    data.process_data_for_paper_model("../User3/030717/Bag_Motion.txt", "Data10Tensors/User3/User3_10tensors_030717_bag.csv")
    data.process_data_for_paper_model("../User3/070717/Bag_Motion.txt", "Data10Tensors/User3/User3_10tensors_070717_bag.csv")

    # User3 hand
    data.process_data_for_paper_model("../User3/140617/Hand_Motion.txt", "Data10Tensors/User3/User3_10tensors_140617_hand.csv")
    data.process_data_for_paper_model("../User3/030717/Hand_Motion.txt", "Data10Tensors/User3/User3_10tensors_030717_hand.csv")
    data.process_data_for_paper_model("../User3/070717/Hand_Motion.txt", "Data10Tensors/User3/User3_10tensors_070717_hand.csv")

    # User3 hips
    data.process_data_for_paper_model("../User3/140617/Hips_Motion.txt", "Data10Tensors/User3/User3_10tensors_140617_hips.csv")
    data.process_data_for_paper_model("../User3/030717/Hips_Motion.txt", "Data10Tensors/User3/User3_10tensors_030717_hips.csv")
    data.process_data_for_paper_model("../User3/070717/Hips_Motion.txt", "Data10Tensors/User3/User3_10tensors_070717_hips.csv")

    DATA_PROCESSED = 1

In [3]:
# ---------------- USER 1 ---------------
# DIA 22/06/17
x_train_user1_220617_hips, y_train_user1_220617_hips, x_test_user1_220617_hips, y_test_user1_220617_hips = data.get_data_and_create_windows("Data10Tensors/User1/User1_10tensors_220617_hips.csv", "../User1/220617/Label_New_User1_220617.txt", title="USER1 HIPS 22/06/17")
print(np.unique(y_train_user1_220617_hips, return_counts=True))
print(np.unique(y_test_user1_220617_hips, return_counts=True))
print("\n\n")

# DIA 26/06/17
x_train_user1_260617_hips, y_train_user1_260617_hips, x_test_user1_260617_hips, y_test_user1_260617_hips = data.get_data_and_create_windows("Data10Tensors/User1/User1_10tensors_260617_hips.csv", "../User1/260617/Label_New_User1_260617.txt", title="USER1 HIPS 26/06/17")
print(np.unique(y_train_user1_260617_hips, return_counts=True))
print(np.unique(y_test_user1_260617_hips, return_counts=True))
print("\n\n")

# DIA 27/06/17
x_train_user1_270617_hips, y_train_user1_270617_hips, x_test_user1_270617_hips, y_test_user1_270617_hips = data.get_data_and_create_windows("Data10Tensors/User1/User1_10tensors_270617_hips.csv", "../User1/270617/Label_New_User1_270617.txt", title="USER1 HIPS 27/06/17")
print(np.unique(y_train_user1_270617_hips, return_counts=True))
print(np.unique(y_test_user1_270617_hips, return_counts=True))
print("\n\n")

# ---------------- USER 2 ---------------
# DIA 14/06/17
x_train_user2_140617_hand, y_train_user2_140617_hand, x_test_user2_140617_hand, y_test_user2_140617_hand = data.get_data_and_create_windows("Data10Tensors/User2/User2_10tensors_140617_hand.csv", "../User2/140617/Label_New_User2_140617.txt", title="USER2 HAND 14/06/17")
print(np.unique(y_train_user2_140617_hand, return_counts=True))
print(np.unique(y_test_user2_140617_hand, return_counts=True))
print("\n\n")

# DIA 14/07/17
x_train_user2_140717_hand, y_train_user2_140717_hand, x_test_user2_140717_hand, y_test_user2_140717_hand = data.get_data_and_create_windows("Data10Tensors/User2/User2_10tensors_140717_hand.csv", "../User2/140717/Label_New_User2_140717.txt", title="USER2 HAND 14/07/17")
print(np.unique(y_train_user2_140717_hand, return_counts=True))
print(np.unique(y_test_user2_140717_hand, return_counts=True))
print("\n\n")

# DIA 18/07/17
x_train_user2_180717_hand, y_train_user2_180717_hand, x_test_user2_180717_hand, y_test_user2_180717_hand = data.get_data_and_create_windows("Data10Tensors/User2/User2_10tensors_180717_hand.csv", "../User2/180717/Label_New_User2_180717.txt", title="USER2 HAND 18/07/17")
print(np.unique(y_train_user2_180717_hand, return_counts=True))
print(np.unique(y_test_user2_180717_hand, return_counts=True))
print("\n\n")

# ---------------- USER 3 ---------------
# DIA 14/06/17
x_train_user3_140617_bag, y_train_user3_140617_bag, x_test_user3_140617_bag, y_test_user3_140617_bag = data.get_data_and_create_windows("Data10Tensors/User3/User3_10tensors_140617_bag.csv", "../User3/140617/Label_New_User3_140617.txt", title="USER3 BAG 14/06/17")
print(np.unique(y_train_user3_140617_bag, return_counts=True))
print(np.unique(y_test_user3_140617_bag, return_counts=True))
print("\n\n")

# DIA 03/07/17
x_train_user3_030717_hips, y_train_user3_030717_hips, x_test_user3_030717_hips, y_test_user3_030717_hips = data.get_data_and_create_windows("Data10Tensors/User3/User3_10tensors_030717_hips.csv", "../User3/030717/Label_New_User3_030717.txt", title="USER3 HIPS 03/07/17")
print(np.unique(y_train_user3_030717_hips, return_counts=True))
print(np.unique(y_test_user3_030717_hips, return_counts=True))
print("\n\n")

# DIA 07/07/17
x_train_user3_070717_hips, y_train_user3_070717_hips, x_test_user3_070717_hips, y_test_user3_070717_hips = data.get_data_and_create_windows("Data10Tensors/User3/User3_10tensors_070717_hips.csv", "../User3/070717/Label_New_User3_070717.txt", title="USER3 HIPS 07/07/17")
print(np.unique(y_train_user3_070717_hips, return_counts=True))
print(np.unique(y_test_user3_070717_hips, return_counts=True))
print("\n\n")


--INFO DE LOS DATOS USER1 HIPS 22/06/17 --
Tamaño dataset: 1825611
Numero de ventanas de entrenamiento:  2555
Forma de las ventanas de entrenamiento: datos --> (2555, 500, 1) ; labels -->  (2555,)
Numero de ventanas de pruebas:  1096
Forma de las ventanas de pruebas: datos -->  (1096, 500, 1) ; labels -->  (1096,)



(array([1, 2, 5, 6]), array([ 501,  533, 1380,  141]))
(array([2, 3, 5]), array([244, 246, 606]))



--INFO DE LOS DATOS USER1 HIPS 26/06/17 --
Tamaño dataset: 2083506
Numero de ventanas de entrenamiento:  2916
Forma de las ventanas de entrenamiento: datos --> (2916, 500, 1) ; labels -->  (2916,)
Numero de ventanas de pruebas:  1251
Forma de las ventanas de pruebas: datos -->  (1251, 500, 1) ; labels -->  (1251,)



(array([1, 2, 3, 4, 6]), array([ 849,  262,   21,  252, 1532]))
(array([2, 4, 6]), array([462, 495, 294]))



--INFO DE LOS DATOS USER1 HIPS 27/06/17 --
Tamaño dataset: 2179610
Numero de ventanas de entrenamiento:  3051
Forma de las ventanas de entrenamiento: d

In [6]:
x_train, x_test, y_train, y_test = data.create_full_train_test_arrays(True, x_train_user1_260617_hips=x_train_user1_260617_hips, x_train_user2_180717_hand=x_train_user2_180717_hand,
                                                                       x_test_user1_260617_hips=x_test_user1_260617_hips, x_test_user2_180717_hand=x_test_user2_180717_hand,
                                                                       y_train_user1_260617=y_train_user1_260617_hips, y_train_user2_180717=y_train_user2_180717_hand,
                                                                       y_test_user1_260617=y_test_user1_260617_hips, y_test_user2_180717=y_test_user2_180717_hand)

input_tensors = [tf.constant(x_train['AcelX']), tf.constant(x_train['AcelY']), tf.constant(x_train['AcelZ']), tf.constant(x_train['MagX']), tf.constant(x_train['MagY']), tf.constant(x_train['MagZ']), tf.constant(x_train['GirosX']), tf.constant(x_train['GirosY']), tf.constant(x_train['GirosZ'])]
input_tensors_test = [tf.constant(x_test['AcelX']), tf.constant(x_test['AcelY']), tf.constant(x_test['AcelZ']), tf.constant(x_test['MagX']), tf.constant(x_test['MagY']), tf.constant(x_test['MagZ']), tf.constant(x_test['GirosX']), tf.constant(x_test['GirosY']), tf.constant(x_test['GirosZ'])]

input_shape = x_train['AcelX'].shape[1:]
print(input_shape)
model_all_data = data.create_model(input_shape)

model_all_data.fit(input_tensors, tf.cast(tf.constant(y_train), tf.float32), epochs=50)

y_pred = model_all_data.predict(input_tensors_test)

from sklearn import metrics

"""y_pred_final = []

for item in y_pred:
    y_pred_final.append(item.arg)"""
accuracy = metrics.accuracy_score(y_test, y_pred.argmax(axis=1))
print(accuracy)
recall = metrics.recall_score(y_test, y_pred.argmax(axis=1), average='weighted', zero_division=0)
print(recall)
precision = metrics.precision_score(y_test, y_pred.argmax(axis=1), average='weighted', zero_division=0)
print(precision)
f1_score = metrics.f1_score(y_test, y_pred.argmax(axis=1), average='weighted')
print(f1_score)

(500, 1)
Input shape (500, 1)
Capa input --> (None, 500, 1)
Capa TCN ---> (None, 500, 32)
Capa MaxPooling ---> (None, 250, 32)
Capa de normalizacion ---> (None, 250, 32)
Capa multi atención ---> (None, 250, 32)
Capa de MHA --> (None, 250, 288)
Capa de convolución --> (None, 250, 64)
Capa de MaxPooling --> (None, 125, 64)
Capa de GAPooling --> (None, 64)
Capa de salida de la red --> (None, 8)
Epoch 1/50
194/194 [==============================] - 73s 122ms/step - loss: 0.3927 - accuracy: 0.8778
Epoch 2/50
194/194 [==============================] - 24s 123ms/step - loss: 0.2304 - accuracy: 0.9287
Epoch 3/50
194/194 [==============================] - 24s 123ms/step - loss: 0.2062 - accuracy: 0.9360
Epoch 4/50
194/194 [==============================] - 24s 123ms/step - loss: 0.1836 - accuracy: 0.9413
Epoch 5/50
194/194 [==============================] - 24s 122ms/step - loss: 0.1880 - accuracy: 0.9425
Epoch 6/50
194/194 [==============================] - 24s 122ms/step - loss: 0.1529 - accu

In [7]:
model_json = model_all_data.to_json()
with open('ModelsMemoFinalNoPres/Modelo2_6/model.json', "w") as json_file:
    json_file.write(model_json)
model_all_data.save_weights('ModelsMemoFinalNoPres/Modelo2_6/weights.h5')